# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f2d37ca9170b4b4fa623f5730b3d3de45e1d415f7050ca1a3da1a96a6f54c878fea5cfcf175cd48743102be7df9557e33083cd89be24f1b89540bf4673fc0b0

test:
  secret_key_base: 4e647a9326365409244309e6d99775a28a7150e33b4ff413e89bcae307df015e7a780d0574ed42d8f65165464a83ccd5379af950ec07eed6be5789841c54ea82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
